openapi: 3.0.0
info:
  title: Bot Backend
  version: 1.0.0
  description: Description
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Audit:
      type: object
      properties:
        id:
          type: integer
        action:
          type: string
          enum:
            - CREATE_USER
        userId:
          type: integer
          default: 1
        actionAt:
          type: string
          format: date-time
        metadata:
          type:
            - number
            - string
            - boolean
            - object
            - array
            - "null"
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type:
            - string
            - "null"
        name:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        password:
          type:
            - string
            - "null"
servers:
  - url: https://http://localhost:3000
    description: Server
paths: {}
tags: []
